[dev-dependencies]
tokio = { version = '1', features = ['macros', 'rt-multi-thread'] }
totp_rfc6238 = "0.6.1"
anyhow = "1"
thiserror = "1"
dotenv = "0.15"
base32 = "0.5.1"

[[test]]
name = "integration"
path = "integration/main.rs"
harness = false