/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiHealth {
    #[serde(rename = "buildVersionTag")]
    pub build_version_tag: String,
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "serverName")]
    pub server_name: String,
}

impl ApiHealth {
    pub fn new(build_version_tag: String, ok: bool, server_name: String) -> ApiHealth {
        ApiHealth {
            build_version_tag,
            ok,
            server_name,
        }
    }
}
