/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiConfigConstants : Constants
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiConfigConstants {
    #[serde(rename = "GROUPS")]
    pub groups: models::ApiConfigConstantsGroups,
    #[serde(rename = "INSTANCE")]
    pub instance: models::ApiConfigConstantsInstance,
    #[serde(rename = "LANGUAGE")]
    pub language: models::ApiConfigConstantsLanguage,
}

impl ApiConfigConstants {
    /// Constants
    pub fn new(
        groups: models::ApiConfigConstantsGroups,
        instance: models::ApiConfigConstantsInstance,
        language: models::ApiConfigConstantsLanguage,
    ) -> ApiConfigConstants {
        ApiConfigConstants {
            groups,
            instance,
            language,
        }
    }
}
