/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiConfigConstantsLanguage : Language-related constants
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiConfigConstantsLanguage {
    /// Supported spoken language options
    #[serde(
        rename = "SPOKEN_LANGUAGE_OPTIONS",
        skip_serializing_if = "Option::is_none"
    )]
    pub spoken_language_options: Option<std::collections::HashMap<String, String>>,
}

impl ApiConfigConstantsLanguage {
    /// Language-related constants
    pub fn new() -> ApiConfigConstantsLanguage {
        ApiConfigConstantsLanguage {
            spoken_language_options: None,
        }
    }
}
