/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AvatarModerationCreated {
    #[serde(rename = "avatarModerationType")]
    pub avatar_moderation_type: models::AvatarModerationType,
    /// Timestamp in milliseconds since Unix epoch
    #[serde(rename = "created")]
    pub created: i64,
    #[serde(rename = "targetAvatarId")]
    pub target_avatar_id: String,
}

impl AvatarModerationCreated {
    pub fn new(
        avatar_moderation_type: models::AvatarModerationType,
        created: i64,
        target_avatar_id: String,
    ) -> AvatarModerationCreated {
        AvatarModerationCreated {
            avatar_moderation_type,
            created,
            target_avatar_id,
        }
    }
}
