/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateFileRequest {
    #[serde(rename = "extension")]
    pub extension: String,
    #[serde(rename = "mimeType")]
    pub mime_type: models::MimeType,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl CreateFileRequest {
    pub fn new(extension: String, mime_type: models::MimeType, name: String) -> CreateFileRequest {
        CreateFileRequest {
            extension,
            mime_type,
            name,
            tags: None,
        }
    }
}
