/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGroupInviteRequest {
    /// A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(
        rename = "confirmOverrideBlock",
        skip_serializing_if = "Option::is_none"
    )]
    pub confirm_override_block: Option<bool>,
}

impl CreateGroupInviteRequest {
    pub fn new(user_id: String) -> CreateGroupInviteRequest {
        CreateGroupInviteRequest {
            user_id,
            confirm_override_block: None,
        }
    }
}
