/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGroupPostRequest {
    #[serde(rename = "imageId", skip_serializing_if = "Option::is_none")]
    pub image_id: Option<String>,
    #[serde(rename = "roleIds", skip_serializing_if = "Option::is_none")]
    pub role_ids: Option<Vec<String>>,
    /// Send notification to group members.
    #[serde(rename = "sendNotification")]
    pub send_notification: bool,
    /// Post text
    #[serde(rename = "text")]
    pub text: String,
    /// Post title
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "visibility")]
    pub visibility: models::GroupPostVisibility,
}

impl CreateGroupPostRequest {
    pub fn new(
        send_notification: bool,
        text: String,
        title: String,
        visibility: models::GroupPostVisibility,
    ) -> CreateGroupPostRequest {
        CreateGroupPostRequest {
            image_id: None,
            role_ids: None,
            send_notification,
            text,
            title,
            visibility,
        }
    }
}
