/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurrentUserPlatformHistoryInner {
    #[serde(rename = "isMobile", skip_serializing_if = "Option::is_none")]
    pub is_mobile: Option<bool>,
    /// This can be `standalonewindows` or `android`, but can also pretty much be any random Unity verison such as `2019.2.4-801-Release` or `2019.2.2-772-Release` or even `unknownplatform`.
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(rename = "recorded", skip_serializing_if = "Option::is_none")]
    pub recorded: Option<String>,
}

impl CurrentUserPlatformHistoryInner {
    pub fn new() -> CurrentUserPlatformHistoryInner {
        CurrentUserPlatformHistoryInner {
            is_mobile: None,
            platform: None,
            recorded: None,
        }
    }
}
