/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: me@ruby.js.org
 * Generated by: https://openapi-generator.tech
 */

/// DeveloperType : \"none\" User is a normal user \"trusted\" Unknown \"internal\" Is a VRChat Developer \"moderator\" Is a VRChat Moderator  Staff can hide their developerType at will.

/// \"none\" User is a normal user \"trusted\" Unknown \"internal\" Is a VRChat Developer \"moderator\" Is a VRChat Moderator  Staff can hide their developerType at will.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeveloperType {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "trusted")]
    Trusted,
    #[serde(rename = "internal")]
    Internal,
    #[serde(rename = "moderator")]
    Moderator,

}

impl ToString for DeveloperType {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("none"),
            Self::Trusted => String::from("trusted"),
            Self::Internal => String::from("internal"),
            Self::Moderator => String::from("moderator"),
        }
    }
}




