/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FavoriteGroupLimits {
    #[serde(rename = "avatar")]
    pub avatar: i32,
    #[serde(rename = "friend")]
    pub friend: i32,
    #[serde(rename = "world")]
    pub world: i32,
}

impl FavoriteGroupLimits {
    pub fn new(avatar: i32, friend: i32, world: i32) -> FavoriteGroupLimits {
        FavoriteGroupLimits {
            avatar,
            friend,
            world,
        }
    }
}
