/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: me@ruby.js.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FavoriteGroup {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "ownerId")]
    pub owner_id: String,
    #[serde(rename = "ownerDisplayName")]
    pub owner_display_name: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "type")]
    pub _type: crate::models::FavoriteType,
    #[serde(rename = "visibility")]
    pub visibility: crate::models::FavoriteGroupVisibility,
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
}

impl FavoriteGroup {
    pub fn new(id: String, owner_id: String, owner_display_name: String, name: String, display_name: String, _type: crate::models::FavoriteType, visibility: crate::models::FavoriteGroupVisibility, tags: Vec<String>) -> FavoriteGroup {
        FavoriteGroup {
            id,
            owner_id,
            owner_display_name,
            name,
            display_name,
            _type,
            visibility,
            tags,
        }
    }
}


