/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: me@ruby.js.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FriendStatus {
    #[serde(rename = "isFriend")]
    pub is_friend: bool,
    #[serde(rename = "outgoingRequest")]
    pub outgoing_request: bool,
    #[serde(rename = "incomingRequest")]
    pub incoming_request: bool,
}

impl FriendStatus {
    pub fn new(is_friend: bool, outgoing_request: bool, incoming_request: bool) -> FriendStatus {
        FriendStatus {
            is_friend,
            outgoing_request,
            incoming_request,
        }
    }
}


