/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetCurrentUser200Response {
    CurrentUser(Box<models::CurrentUser>),
    TwoFactorRequired(Box<models::TwoFactorRequired>),
}

impl Default for GetCurrentUser200Response {
    fn default() -> Self {
        Self::CurrentUser(Default::default())
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequiresTwoFactorAuth {
    #[serde(rename = "totp")]
    Totp,
    #[serde(rename = "otp")]
    Otp,
    #[serde(rename = "emailOtp")]
    EmailOtp,
}

impl Default for RequiresTwoFactorAuth {
    fn default() -> RequiresTwoFactorAuth {
        Self::Totp
    }
}

