/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GroupRoleTemplate {
    #[serde(rename = "default")]
    Default,
    #[serde(rename = "managedFree")]
    ManagedFree,
    #[serde(rename = "managedInvite")]
    ManagedInvite,
    #[serde(rename = "managedRequest")]
    ManagedRequest,

}

impl ToString for GroupRoleTemplate {
    fn to_string(&self) -> String {
        match self {
            Self::Default => String::from("default"),
            Self::ManagedFree => String::from("managedFree"),
            Self::ManagedInvite => String::from("managedInvite"),
            Self::ManagedRequest => String::from("managedRequest"),
        }
    }
}

impl Default for GroupRoleTemplate {
    fn default() -> GroupRoleTemplate {
        Self::Default
    }
}




