/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GroupPostVisibility {
    #[serde(rename = "group")]
    Group,
    #[serde(rename = "public")]
    Public,
}

impl std::fmt::Display for GroupPostVisibility {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Group => write!(f, "group"),
            Self::Public => write!(f, "public"),
        }
    }
}

impl Default for GroupPostVisibility {
    fn default() -> GroupPostVisibility {
        Self::Group
    }
}
