/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageAnimationStyle : Animation style for images.
/// Animation style for images.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImageAnimationStyle {
    #[serde(rename = "aura")]
    Aura,
    #[serde(rename = "bats")]
    Bats,
    #[serde(rename = "bees")]
    Bees,
    #[serde(rename = "bounce")]
    Bounce,
    #[serde(rename = "cloud")]
    Cloud,
    #[serde(rename = "confetti")]
    Confetti,
    #[serde(rename = "crying")]
    Crying,
    #[serde(rename = "dislike")]
    Dislike,
    #[serde(rename = "fire")]
    Fire,
    #[serde(rename = "idea")]
    Idea,
    #[serde(rename = "lasers")]
    Lasers,
    #[serde(rename = "like")]
    Like,
    #[serde(rename = "magnet")]
    Magnet,
    #[serde(rename = "mistletoe")]
    Mistletoe,
    #[serde(rename = "money")]
    Money,
    #[serde(rename = "noise")]
    Noise,
    #[serde(rename = "orbit")]
    Orbit,
    #[serde(rename = "pizza")]
    Pizza,
    #[serde(rename = "rain")]
    Rain,
    #[serde(rename = "rotate")]
    Rotate,
    #[serde(rename = "shake")]
    Shake,
    #[serde(rename = "snow")]
    Snow,
    #[serde(rename = "snowball")]
    Snowball,
    #[serde(rename = "spin")]
    Spin,
    #[serde(rename = "splash")]
    Splash,
    #[serde(rename = "stop")]
    Stop,
    #[serde(rename = "zzz")]
    Zzz,
}

impl std::fmt::Display for ImageAnimationStyle {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Aura => write!(f, "aura"),
            Self::Bats => write!(f, "bats"),
            Self::Bees => write!(f, "bees"),
            Self::Bounce => write!(f, "bounce"),
            Self::Cloud => write!(f, "cloud"),
            Self::Confetti => write!(f, "confetti"),
            Self::Crying => write!(f, "crying"),
            Self::Dislike => write!(f, "dislike"),
            Self::Fire => write!(f, "fire"),
            Self::Idea => write!(f, "idea"),
            Self::Lasers => write!(f, "lasers"),
            Self::Like => write!(f, "like"),
            Self::Magnet => write!(f, "magnet"),
            Self::Mistletoe => write!(f, "mistletoe"),
            Self::Money => write!(f, "money"),
            Self::Noise => write!(f, "noise"),
            Self::Orbit => write!(f, "orbit"),
            Self::Pizza => write!(f, "pizza"),
            Self::Rain => write!(f, "rain"),
            Self::Rotate => write!(f, "rotate"),
            Self::Shake => write!(f, "shake"),
            Self::Snow => write!(f, "snow"),
            Self::Snowball => write!(f, "snowball"),
            Self::Spin => write!(f, "spin"),
            Self::Splash => write!(f, "splash"),
            Self::Stop => write!(f, "stop"),
            Self::Zzz => write!(f, "zzz"),
        }
    }
}

impl Default for ImageAnimationStyle {
    fn default() -> ImageAnimationStyle {
        Self::Aura
    }
}
