/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageMask : Mask shape for images.
/// Mask shape for images.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImageMask {
    #[serde(rename = "circle")]
    Circle,
    #[serde(rename = "flower")]
    Flower,
    #[serde(rename = "heart")]
    Heart,
    #[serde(rename = "pow")]
    Pow,
    #[serde(rename = "square")]
    Square,
    #[serde(rename = "star")]
    Star,
}

impl std::fmt::Display for ImageMask {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Circle => write!(f, "circle"),
            Self::Flower => write!(f, "flower"),
            Self::Heart => write!(f, "heart"),
            Self::Pow => write!(f, "pow"),
            Self::Square => write!(f, "square"),
            Self::Star => write!(f, "star"),
        }
    }
}

impl Default for ImageMask {
    fn default() -> ImageMask {
        Self::Circle
    }
}
