/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: me@ruby.js.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse403 {
    #[serde(rename = "error")]
    pub error: Box<crate::models::Error>,
}

impl InlineResponse403 {
    pub fn new(error: crate::models::Error) -> InlineResponse403 {
        InlineResponse403 {
            error: Box::new(error),
        }
    }
}


