/*
 * VRChat API Documentation
 *
 *
 * Contact: me@ruby.js.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineObject {
    #[serde(rename = "code")]
    pub code: String,
}

impl InlineObject {
    pub fn new(code: String) -> InlineObject {
        InlineObject {
            code,
        }
    }
}


