/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: me@ruby.js.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject5 {
    /// Array of ETags uploaded.
    #[serde(rename = "etags", skip_serializing_if = "Option::is_none")]
    pub etags: Option<Vec<String>>,
    /// Always a zero in string form, despite how many parts uploaded.
    #[serde(rename = "nextPartNumber")]
    pub next_part_number: String,
    /// Always a zero in string form, despite how many parts uploaded.
    #[serde(rename = "maxParts")]
    pub max_parts: String,
}

impl InlineObject5 {
    pub fn new(next_part_number: String, max_parts: String) -> InlineObject5 {
        InlineObject5 {
            etags: None,
            next_part_number,
            max_parts,
        }
    }
}


