/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.4.1
 * Contact: me@ruby.js.org
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InviteMessageType {
    #[serde(rename = "message")]
    Message,

}

impl ToString for InviteMessageType {
    fn to_string(&self) -> String {
        match self {
            Self::Message => String::from("message"),
        }
    }
}




