/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct License {
    #[serde(rename = "forAction")]
    pub for_action: models::LicenseAction,
    /// Either a AvatarID, LicenseGroupID, PermissionID or ProductID. This depends on the `forType` field.
    #[serde(rename = "forId")]
    pub for_id: String,
    #[serde(rename = "forName")]
    pub for_name: String,
    #[serde(rename = "forType")]
    pub for_type: models::LicenseType,
}

impl License {
    pub fn new(
        for_action: models::LicenseAction,
        for_id: String,
        for_name: String,
        for_type: models::LicenseType,
    ) -> License {
        License {
            for_action,
            for_id,
            for_name,
            for_type,
        }
    }
}
