/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LimitedUserFriend : User object received when querying your friends list
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LimitedUserFriend {
    #[serde(rename = "bio", skip_serializing_if = "Option::is_none")]
    pub bio: Option<String>,
    #[serde(rename = "bioLinks", skip_serializing_if = "Option::is_none")]
    pub bio_links: Option<Vec<String>>,
    /// When profilePicOverride is not empty, use it instead.
    #[serde(
        rename = "currentAvatarImageUrl",
        skip_serializing_if = "Option::is_none"
    )]
    pub current_avatar_image_url: Option<String>,
    #[serde(rename = "currentAvatarTags", skip_serializing_if = "Option::is_none")]
    pub current_avatar_tags: Option<Vec<String>>,
    /// When profilePicOverride is not empty, use it instead.
    #[serde(
        rename = "currentAvatarThumbnailImageUrl",
        skip_serializing_if = "Option::is_none"
    )]
    pub current_avatar_thumbnail_image_url: Option<String>,
    #[serde(rename = "developerType")]
    pub developer_type: models::DeveloperType,
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "friendKey")]
    pub friend_key: String,
    /// A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "imageUrl")]
    pub image_url: String,
    #[serde(rename = "isFriend")]
    pub is_friend: bool,
    #[serde(rename = "last_activity", deserialize_with = "Option::deserialize")]
    pub last_activity: Option<String>,
    #[serde(rename = "last_login", deserialize_with = "Option::deserialize")]
    pub last_login: Option<String>,
    #[serde(rename = "last_mobile", deserialize_with = "Option::deserialize")]
    pub last_mobile: Option<String>,
    /// This is normally `android`, `ios`, `standalonewindows`, `web`, or the empty value ``, but also supposedly can be any random Unity verison such as `2019.2.4-801-Release` or `2019.2.2-772-Release` or even `unknownplatform`.
    #[serde(rename = "last_platform")]
    pub last_platform: String,
    #[serde(rename = "location")]
    pub location: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "profilePicOverride", skip_serializing_if = "Option::is_none")]
    pub profile_pic_override: Option<String>,
    #[serde(
        rename = "profilePicOverrideThumbnail",
        skip_serializing_if = "Option::is_none"
    )]
    pub profile_pic_override_thumbnail: Option<String>,
    #[serde(rename = "status")]
    pub status: models::UserStatus,
    #[serde(rename = "statusDescription")]
    pub status_description: String,
    /// <- Always empty.
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    #[serde(rename = "userIcon", skip_serializing_if = "Option::is_none")]
    pub user_icon: Option<String>,
}

impl LimitedUserFriend {
    /// User object received when querying your friends list
    pub fn new(
        developer_type: models::DeveloperType,
        display_name: String,
        friend_key: String,
        id: String,
        image_url: String,
        is_friend: bool,
        last_activity: Option<String>,
        last_login: Option<String>,
        last_mobile: Option<String>,
        last_platform: String,
        location: String,
        platform: String,
        status: models::UserStatus,
        status_description: String,
        tags: Vec<String>,
    ) -> LimitedUserFriend {
        LimitedUserFriend {
            bio: None,
            bio_links: None,
            current_avatar_image_url: None,
            current_avatar_tags: None,
            current_avatar_thumbnail_image_url: None,
            developer_type,
            display_name,
            friend_key,
            id,
            image_url,
            is_friend,
            last_activity,
            last_login,
            last_mobile,
            last_platform,
            location,
            platform,
            profile_pic_override: None,
            profile_pic_override_thumbnail: None,
            status,
            status_description,
            tags,
            user_icon: None,
        }
    }
}
