/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotificationDetailBoop : Either inventoryItemId by itself, or emojiId with optional emojiVersion
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationDetailBoop {
    #[serde(rename = "emojiId", skip_serializing_if = "Option::is_none")]
    pub emoji_id: Option<String>,
    #[serde(rename = "emojiVersion", skip_serializing_if = "Option::is_none")]
    pub emoji_version: Option<i32>,
    #[serde(rename = "inventoryItemId", skip_serializing_if = "Option::is_none")]
    pub inventory_item_id: Option<String>,
}

impl NotificationDetailBoop {
    /// Either inventoryItemId by itself, or emojiId with optional emojiVersion
    pub fn new() -> NotificationDetailBoop {
        NotificationDetailBoop {
            emoji_id: None,
            emoji_version: None,
            inventory_item_id: None,
        }
    }
}
