/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationV2DataGroupTransfer {
    #[serde(rename = "groupName")]
    pub group_name: String,
    #[serde(rename = "ownerUserDisplayName")]
    pub owner_user_display_name: String,
}

impl NotificationV2DataGroupTransfer {
    pub fn new(
        group_name: String,
        owner_user_display_name: String,
    ) -> NotificationV2DataGroupTransfer {
        NotificationV2DataGroupTransfer {
            group_name,
            owner_user_display_name,
        }
    }
}
