/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationV2DataBadgeEarned {
    #[serde(rename = "badgeDescription")]
    pub badge_description: String,
    #[serde(rename = "badgeId")]
    pub badge_id: String,
    #[serde(rename = "badgeName")]
    pub badge_name: String,
}

impl NotificationV2DataBadgeEarned {
    pub fn new(
        badge_description: String,
        badge_id: String,
        badge_name: String,
    ) -> NotificationV2DataBadgeEarned {
        NotificationV2DataBadgeEarned {
            badge_description,
            badge_id,
            badge_name,
        }
    }
}
