/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: me@ruby.js.org
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NotificationType {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "broadcast")]
    Broadcast,
    #[serde(rename = "friendRequest")]
    FriendRequest,
    #[serde(rename = "invite")]
    Invite,
    #[serde(rename = "message")]
    Message,
    #[serde(rename = "RequestInvite")]
    RequestInvite,
    #[serde(rename = "votetokick")]
    Votetokick,

}

impl ToString for NotificationType {
    fn to_string(&self) -> String {
        match self {
            Self::All => String::from("all"),
            Self::Broadcast => String::from("broadcast"),
            Self::FriendRequest => String::from("friendRequest"),
            Self::Invite => String::from("invite"),
            Self::Message => String::from("message"),
            Self::RequestInvite => String::from("RequestInvite"),
            Self::Votetokick => String::from("votetokick"),
        }
    }
}




