/*
 * VRChat API Documentation
 *
 *
 * Contact: me@ariesclark.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderOption {
    #[serde(rename = "ascending")]
    Ascending,
    #[serde(rename = "descending")]
    Descending,

}

impl ToString for OrderOption {
    fn to_string(&self) -> String {
        match self {
            Self::Ascending => String::from("ascending"),
            Self::Descending => String::from("descending"),
        }
    }
}

impl Default for OrderOption {
    fn default() -> OrderOption {
        Self::Ascending
    }
}




