/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: me@ruby.js.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PastDisplayName {
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl PastDisplayName {
    pub fn new(display_name: String, updated_at: String) -> PastDisplayName {
        PastDisplayName {
            display_name,
            updated_at,
        }
    }
}


