/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PerformanceLimiterInfo : Info about the performance limits on a platform
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerformanceLimiterInfo {
    /// Maximum amount of seats. -1 means no limit.
    #[serde(rename = "maxSeats")]
    pub max_seats: i32,
}

impl PerformanceLimiterInfo {
    /// Info about the performance limits on a platform
    pub fn new(max_seats: i32) -> PerformanceLimiterInfo {
        PerformanceLimiterInfo { max_seats }
    }
}
