/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProductListingType {
    #[serde(rename = "subscription")]
    Subscription,
}

impl std::fmt::Display for ProductListingType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Subscription => write!(f, "subscription"),
        }
    }
}

impl Default for ProductListingType {
    fn default() -> ProductListingType {
        Self::Subscription
    }
}
