/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: me@ruby.js.org
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Response {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "status_code")]
    pub status_code: f32,
}

impl Response {
    pub fn new(message: String, status_code: f32) -> Response {
        Response {
            message,
            status_code,
        }
    }
}


