/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum StoreType {
    #[serde(rename = "house")]
    House,
    #[serde(rename = "world")]
    World,
    #[serde(rename = "group")]
    Group,
}

impl std::fmt::Display for StoreType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::House => write!(f, "house"),
            Self::World => write!(f, "world"),
            Self::Group => write!(f, "group"),
        }
    }
}

impl Default for StoreType {
    fn default() -> StoreType {
        Self::House
    }
}
