/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Success {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<Box<crate::models::Response>>,
}

impl Success {
    pub fn new() -> Success {
        Success {
            success: None,
        }
    }
}


