/*
 * VRChat API Documentation
 *
 *
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateInviteMessageRequest {
    #[serde(rename = "message")]
    pub message: String,
}

impl UpdateInviteMessageRequest {
    pub fn new(message: String) -> UpdateInviteMessageRequest {
        UpdateInviteMessageRequest {
            message,
        }
    }
}


