on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_call:
    inputs:
      ref:
        description: Ref of this repository to build.
        required: false
        type: string
        default: main

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: vrchatapi/vrchatapi-rust
          ref: ${{ inputs.ref || github.ref }}

      - uses: vrchatapi/specification/.github/actions/setup@ci/modernise-actions
        with:
          generator: 7.21.0

      - uses: actions/setup-java@v5.7.0
        with:
          java-version: '20'
          distribution: temurin

      - uses: moonrepo/setup-rust@v1.3.0

      - run: bash ./generate.sh openapi.json

      - run: cargo build
