on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_call:
    inputs:
      ref:
        description: Ref of this repository to build.
        required: false
        type: string
        default: main

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: vrchatapi/vrchatapi-rust
          ref: ${{ inputs.ref || github.ref }}

      - uses: vrchatapi/specification/.github/actions/setup-generator@ci/modernise-actions

      - uses: vrchatapi/specification/.github/actions/download@ci/modernise-actions

      - uses: moonrepo/setup-rust@v1.3.0

      - run: bash ./generate.sh openapi.json
