on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
    inputs:
      ref:
        description: Ref of this repository to build.
        required: false
        type: string
        default: main

name: CI

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: vrchatapi/vrchatapi-rust
          ref: ${{ inputs.ref || github.ref }}

      - uses: vrchatapi/specification/.github/actions/setup-generator@ci/modernise-actions

      - uses: vrchatapi/specification/.github/actions/download@ci/modernise-actions

      - run: bash ./generate.sh openapi.json

      - uses: actions/upload-artifact@v7
        with:
          name: generated-rust
          path: .
          include-hidden-files: true

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: vrchatapi/vrchatapi-rust
          ref: ${{ inputs.ref || github.ref }}

      - uses: moonrepo/setup-rust@v1.3.0
        with:
          components: rustfmt

      - run: cargo fmt --all -- --check

      - run: rustfmt --edition 2021 --check patches/*.rs

  test:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: generated-rust

      - uses: moonrepo/setup-rust@v1.3.0

      - run: cargo test --all
