name: CI Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6
      - name: Configure sccache env var and set build profile to ephemeral build
        run: |
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
      - run: cargo build --all
      - run: cargo test --all

  check-fmt:
    runs-on: ubuntu-latest
    name: Check formatting
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
